### ISSUE TITLE
Login para relatórios PGDAS (Simples Nacional no ECAC)

### ISSUE THREAD

**Issue by henriquemeira** [servicosgovbr/manual-roteiro-integracao-login-unico#19]
Estou tentando desenvolver uma integração automática com o ECAC para extrair relatórios e guias para pagamento (PGDAS) de empresas do Simples Nacional.

Estou com problemas na autenticação, utilizando o certificado digital A1.

Minha dúvida é: este Manual Roteiro Integração Login Único é indicado para este tipo de atividade? Ou seja, realizar o login no ECAC e consumir os serviços ali disponiveis?

Obrigado.

**Comment by henriquemeira** [comment]
Exemplo de uso:
Via browser, acessar o URL: 
https://sinac.cav.receita.fazenda.gov.br/SimplesNacional/Aplicacoes/ATSPO/pgdasd2018.app/Consulta/ExtratoDetalhado?numeroDocumento=07202104377555971&tipoDas=4&ano=2020

1. No primeiro acesso, o browser é redirecionado para a tela de login do Gov.BR
2. Clica-se no login utilizando o certificado digital
3. Após a seleção do certificado, o browser é redirecionado para o portal do ECAC, já logado.
4. Cola novamente a URL desejada e o relatório é exibido.

A minha dúvida é se eu posso utilizar as orientações de INTEGRAÇÃO LOGIN ÚNICO deste projeto para realizar esta atividade, ou se este não é o formato de LOGIN necessário para utilização com o PGDAS.

Obrigado.

**Comment by caduvieira** [comment]
> Estou tentando desenvolver uma integração automática com o ECAC para extrair relatórios e guias para pagamento (PGDAS) de empresas do Simples Nacional.
> 
> Estou com problemas na autenticação, utilizando o certificado digital A1.
> 
> Minha dúvida é: este Manual Roteiro Integração Login Único é indicado para este tipo de atividade? Ou seja, realizar o login no ECAC e consumir os serviços ali disponiveis?
> 
> Obrigado.

O manual de integração é para integrar via OAUTH2 os sistemas da Administração pública para que a população possa utilizar o login gov.br e acessar os serviços digitais da aministração. A integração aqui é dos órgãos da administração pública com o login gov.br. Para automatizar o acesso a algum serviço sem intervernção humana da Receita sugiro entrar em contato com a própria receita para verificar a disponibilidade de alguma API do serviço PGDAS.

**Comment by henriquemeira** [comment]
Obrigado.
