### ISSUE TITLE
PHP - Criação de exemplo básico de requisições para Login Único utilizando código fonte PHP 

### ISSUE THREAD

**Issue by JoabioVilela** [servicosgovbr/manual-roteiro-integracao-login-unico#21]
Pretendo criar código fonte em linguagem PHP (nativo) que sirva de exemplo básico de requisições para Login Único.

Quem tiver interesse em participar, fale comigo através do meu e-mail:

joabio.vilela@gmail.com

**Comment by weltonrodrigo** [comment]
Se você quiser, poderia criar um repo público pra isso e fazer do PHP em uma pasta e aceitar pull requests pra outras linguagens e frameworks. Eu poderia incluir um exemplo com spring security
