### ISSUE TITLE
Problema no redirect logout

### ISSUE THREAD

**Issue by betosantin** [servicosgovbr/manual-roteiro-integracao-login-unico#38]
Olá, estou com um problema ao efetuar o logout.

A url que cadastrei na plataforma para a minha secret é: "https://minhaUrl/home.faces"
Ao efetuar o logout o usuário não é direcionado para a minha aplicação.

Exemplo não funcional (não faz o redirect para minha aplicação):
"https://sso.staging.acesso.gov.br/logout?post_logout_redirect_uri=https://minhaUrl/home.faces?tipoAutenticacao=GOV".

URL com encode:
"https://sso.staging.acesso.gov.br/logout?post_logout_redirect_uri=https%3A%2F%2FminhaUrl%2Fhome.faces%3FtipoAutenticacao%3DGOV"

Ao utilizar a mesma url sem path parameter o redirect é executado:
"https://sso.staging.acesso.gov.br/logout?post_logout_redirect_uri=https://minhaUrl/home.faces"

URL com encode:
"https://sso.staging.acesso.gov.br/logout?post_logout_redirect_uri=https%3A%2F%2FminhaUrl%2Fhome.faces"

Note que tenho um path parameter para direcionar o usuário para página correta de logout. Tenho diferentes páginas de logout com necessidades de exibição de diferentes informações, dependendo do local que o usuário realizou o login, por isso da utilização do path parameter.

Agradeço qualquer ajuda para solução do problema.

**Comment by weltonrodrigo** [comment]
A issue foi fechada, mas vale a pena destacar que o a `post_logout_redirect_uri` deve casar **EXATAMENTE** com o valor cadastrado previamente.

A seção relevante na especificação: https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RedirectionAfterLogout:~:text=The%20OP%20also%20MUST%20NOT%20perform%20post%2Dlogout%20redirection%20if%20the%20post_logout_redirect_uri%20value%20supplied%20does%20not%20exactly%20match%20one%20of%20the%20previously%20registered%20post_logout_redirect_uris%20values

Uma parte do motivo pelo qual as urls de redirecionamento não devem aceitar matches parciais (ou wildcard) está aqui https://datatracker.ietf.org/doc/html/rfc6819#section-5.2.3.5 e aqui https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#name-protecting-redirect-based-f

No seu caso em questão, você pode registrar uma `post_logout_redirect_uri` para cada caso.

**Comment by betosantin** [comment]
Obrigado pela resposta Welton.

Depois que fechei, realmente li a RFC e vi que tratava-se especialmente por possíveis problemas de segurança. O único impecílio, é solicitar para todos os clientes (mais de 50 clientes) registrar novas URLs (mas será resolvido adicionando novas urls) 

Novamente, obrigado pela sua resposta.
